@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTIzMTI1OTJ9.GFZ2cmT4lVhd6lItv_HxmIpYB-huOISvLzByCOlCMmU

### Users Index
GET http://localhost:3000/users.json


### users create

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "john",
  "email": "test@test.com",
  "password": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### favorites Index
GET http://localhost:3000/favorites.json

###favorites create
POST http://localhost:3000/favorites.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "champion_name": "aatrox",
  "mythic_name": "Goredrinker"


}
###favorites update
PATCH http://localhost:3000/favorites/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTIzMDgyMjN9.pTEwxwYHTjtHbg7GFELFgGIm1uzGb_KVfwKstrG7XI4
Content-Type: application/json

{
  "champion_name": "quinn"
}

###favorites delete
DELETE http://localhost:3000/favorites/2.json

###champions Index
GET http://localhost:3000/champions

###items Index
GET http://localhost:3000/items

###player_info
GET http://localhost:3000/favorites/player_info/puddn


###items
GET http://localhost:3000/favorites/
